# Generated by Django 4.0.4 on 2024-03-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_alter_customer_sex_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(choices=[('0-15', '0-15'), ('15-25', '15-25')], max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
